import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const industries: { sector: string; name: string }[] = [
  // Technology
  { sector: "Technology", name: "Artificial Intelligence" },
  { sector: "Technology", name: "Blockchain" },
  { sector: "Technology", name: "Cloud Computing" },
  { sector: "Technology", name: "Consumer Electronics" },
  { sector: "Technology", name: "Cybersecurity" },
  { sector: "Technology", name: "Data Analytics" },
  { sector: "Technology", name: "DevOps" },
  { sector: "Technology", name: "Enterprise Software" },
  { sector: "Technology", name: "FinTech" },
  { sector: "Technology", name: "Gaming" },
  { sector: "Technology", name: "Hardware Manufacturing" },
  { sector: "Technology", name: "IT Consulting" },
  { sector: "Technology", name: "Machine Learning" },
  { sector: "Technology", name: "Mobile Apps" },
  { sector: "Technology", name: "SaaS" },
  { sector: "Technology", name: "Semiconductor Manufacturing" },
  { sector: "Technology", name: "Software Development" },
  { sector: "Technology", name: "Telecommunications" },
  { sector: "Technology", name: "Web Development" },
  { sector: "Technology", name: "Internet of Things (IoT)" },
  { sector: "Technology", name: "Robotics" },
  { sector: "Technology", name: "Virtual Reality (VR)" },
  { sector: "Technology", name: "Augmented Reality (AR)" },

  // Healthcare
  { sector: "Healthcare", name: "Ambulance Services" },
  { sector: "Healthcare", name: "Audiology" },
  { sector: "Healthcare", name: "Cardiology" },
  { sector: "Healthcare", name: "Clinics" },
  { sector: "Healthcare", name: "Dentistry" },
  { sector: "Healthcare", name: "Dermatology" },
  { sector: "Healthcare", name: "Diagnostic Laboratories" },
  { sector: "Healthcare", name: "Hospitals" },
  { sector: "Healthcare", name: "Medical Devices" },
  { sector: "Healthcare", name: "Mental Health" },
  { sector: "Healthcare", name: "Nursing Homes" },
  { sector: "Healthcare", name: "Optometry" },
  { sector: "Healthcare", name: "Pediatrics" },
  { sector: "Healthcare", name: "Pharmacy" },
  { sector: "Healthcare", name: "Physiotherapy" },
  { sector: "Healthcare", name: "Radiology" },
  { sector: "Healthcare", name: "Telemedicine" },
  { sector: "Healthcare", name: "Veterinary Services" },
  { sector: "Healthcare", name: "Health Insurance" },
  { sector: "Healthcare", name: "Medical Research" },

  // Finance
  { sector: "Finance", name: "Accounting" },
  { sector: "Finance", name: "Asset Management" },
  { sector: "Finance", name: "Banking" },
  { sector: "Finance", name: "Capital Markets" },
  { sector: "Finance", name: "Commodities Trading" },
  { sector: "Finance", name: "Corporate Finance" },
  { sector: "Finance", name: "Credit Services" },
  { sector: "Finance", name: "Cryptocurrency" },
  { sector: "Finance", name: "Financial Advisory" },
  { sector: "Finance", name: "Financial Planning" },
  { sector: "Finance", name: "Hedge Funds" },
  { sector: "Finance", name: "Insurance" },
  { sector: "Finance", name: "Investment Banking" },
  { sector: "Finance", name: "Microfinance" },
  { sector: "Finance", name: "Mortgage & Lending" },
  { sector: "Finance", name: "Payment Processing" },
  { sector: "Finance", name: "Private Equity" },
  { sector: "Finance", name: "Tax Services" },
  { sector: "Finance", name: "Venture Capital" },
  { sector: "Finance", name: "Wealth Management" },

  // Education
  { sector: "Education", name: "Adult Education" },
  { sector: "Education", name: "Corporate Training" },
  { sector: "Education", name: "E-Learning" },
  { sector: "Education", name: "Early Childhood Education" },
  { sector: "Education", name: "EdTech" },
  { sector: "Education", name: "Higher Education" },
  { sector: "Education", name: "K-12 Education" },
  { sector: "Education", name: "Language Learning" },
  { sector: "Education", name: "Online Tutoring" },
  { sector: "Education", name: "Professional Certification" },
  { sector: "Education", name: "Special Education" },
  { sector: "Education", name: "STEM Education" },
  { sector: "Education", name: "Test Preparation" },
  { sector: "Education", name: "Vocational Training" },

  // Real Estate
  { sector: "Real Estate", name: "Commercial Real Estate" },
  { sector: "Real Estate", name: "Construction" },
  { sector: "Real Estate", name: "Facility Management" },
  { sector: "Real Estate", name: "Interior Design" },
  { sector: "Real Estate", name: "Land Development" },
  { sector: "Real Estate", name: "Property Management" },
  { sector: "Real Estate", name: "Real Estate Agency" },
  { sector: "Real Estate", name: "Real Estate Investment" },
  { sector: "Real Estate", name: "Residential Real Estate" },
  { sector: "Real Estate", name: "Urban Planning" },
  { sector: "Real Estate", name: "Architecture" },

  // Retail & E-Commerce
  { sector: "Retail & E-Commerce", name: "Brick-and-Mortar Retail" },
  { sector: "Retail & E-Commerce", name: "Dropshipping" },
  { sector: "Retail & E-Commerce", name: "E-Commerce" },
  { sector: "Retail & E-Commerce", name: "Fashion Retail" },
  { sector: "Retail & E-Commerce", name: "Grocery & Supermarkets" },
  { sector: "Retail & E-Commerce", name: "Luxury Goods" },
  { sector: "Retail & E-Commerce", name: "Marketplace Platforms" },
  { sector: "Retail & E-Commerce", name: "Sporting Goods" },
  { sector: "Retail & E-Commerce", name: "Subscription Boxes" },
  { sector: "Retail & E-Commerce", name: "Wholesale & Distribution" },

  // Media & Entertainment
  { sector: "Media & Entertainment", name: "Advertising" },
  { sector: "Media & Entertainment", name: "Animation" },
  { sector: "Media & Entertainment", name: "Broadcasting" },
  { sector: "Media & Entertainment", name: "Content Creation" },
  { sector: "Media & Entertainment", name: "Digital Marketing" },
  { sector: "Media & Entertainment", name: "Film Production" },
  { sector: "Media & Entertainment", name: "Journalism" },
  { sector: "Media & Entertainment", name: "Music" },
  { sector: "Media & Entertainment", name: "Podcasting" },
  { sector: "Media & Entertainment", name: "Public Relations" },
  { sector: "Media & Entertainment", name: "Publishing" },
  { sector: "Media & Entertainment", name: "Social Media" },
  { sector: "Media & Entertainment", name: "Sports" },
  { sector: "Media & Entertainment", name: "Streaming Services" },
  { sector: "Media & Entertainment", name: "Video Production" },

  // Manufacturing
  { sector: "Manufacturing", name: "Aerospace Manufacturing" },
  { sector: "Manufacturing", name: "Automotive Manufacturing" },
  { sector: "Manufacturing", name: "Chemical Manufacturing" },
  { sector: "Manufacturing", name: "Consumer Goods Manufacturing" },
  { sector: "Manufacturing", name: "Electronics Manufacturing" },
  { sector: "Manufacturing", name: "Food & Beverage Manufacturing" },
  { sector: "Manufacturing", name: "Industrial Machinery" },
  { sector: "Manufacturing", name: "Metal Fabrication" },
  { sector: "Manufacturing", name: "Packaging" },
  { sector: "Manufacturing", name: "Pharmaceutical Manufacturing" },
  { sector: "Manufacturing", name: "Plastics Manufacturing" },
  { sector: "Manufacturing", name: "Textile Manufacturing" },

  // Energy
  { sector: "Energy", name: "Clean Energy" },
  { sector: "Energy", name: "Coal Mining" },
  { sector: "Energy", name: "Energy Storage" },
  { sector: "Energy", name: "Hydropower" },
  { sector: "Energy", name: "Natural Gas" },
  { sector: "Energy", name: "Nuclear Energy" },
  { sector: "Energy", name: "Oil & Gas" },
  { sector: "Energy", name: "Solar Energy" },
  { sector: "Energy", name: "Utilities" },
  { sector: "Energy", name: "Wind Energy" },

  // Transportation & Logistics
  { sector: "Transportation & Logistics", name: "Air Freight" },
  { sector: "Transportation & Logistics", name: "Airlines" },
  { sector: "Transportation & Logistics", name: "Courier Services" },
  { sector: "Transportation & Logistics", name: "Fleet Management" },
  { sector: "Transportation & Logistics", name: "Freight Brokerage" },
  { sector: "Transportation & Logistics", name: "Last-Mile Delivery" },
  { sector: "Transportation & Logistics", name: "Maritime Shipping" },
  { sector: "Transportation & Logistics", name: "Public Transit" },
  { sector: "Transportation & Logistics", name: "Railroads" },
  { sector: "Transportation & Logistics", name: "Supply Chain Management" },
  { sector: "Transportation & Logistics", name: "Trucking" },
  { sector: "Transportation & Logistics", name: "Warehousing" },

  // Food & Beverage
  { sector: "Food & Beverage", name: "Bakeries" },
  { sector: "Food & Beverage", name: "Bars & Nightclubs" },
  { sector: "Food & Beverage", name: "Catering" },
  { sector: "Food & Beverage", name: "Coffee Shops" },
  { sector: "Food & Beverage", name: "Fast Food" },
  { sector: "Food & Beverage", name: "Fine Dining" },
  { sector: "Food & Beverage", name: "Food Delivery" },
  { sector: "Food & Beverage", name: "Food Technology" },
  { sector: "Food & Beverage", name: "Organic Food" },
  { sector: "Food & Beverage", name: "Restaurants" },
  { sector: "Food & Beverage", name: "Snacks & Confectionery" },
  { sector: "Food & Beverage", name: "Supermarkets" },

  // Professional Services
  { sector: "Professional Services", name: "Business Consulting" },
  { sector: "Professional Services", name: "Engineering Consulting" },
  { sector: "Professional Services", name: "Environmental Consulting" },
  { sector: "Professional Services", name: "HR & Recruitment" },
  { sector: "Professional Services", name: "IT Consulting" },
  { sector: "Professional Services", name: "Legal Services" },
  { sector: "Professional Services", name: "Management Consulting" },
  { sector: "Professional Services", name: "Market Research" },
  { sector: "Professional Services", name: "Outsourcing" },
  { sector: "Professional Services", name: "Staffing & Recruiting" },
  { sector: "Professional Services", name: "Strategy Consulting" },
  { sector: "Professional Services", name: "Translation Services" },

  // Creative & Design
  { sector: "Creative & Design", name: "Brand Design" },
  { sector: "Creative & Design", name: "Fashion Design" },
  { sector: "Creative & Design", name: "Graphic Design" },
  { sector: "Creative & Design", name: "Industrial Design" },
  { sector: "Creative & Design", name: "Interior Design" },
  { sector: "Creative & Design", name: "Motion Graphics" },
  { sector: "Creative & Design", name: "Photography" },
  { sector: "Creative & Design", name: "Product Design" },
  { sector: "Creative & Design", name: "UI/UX Design" },
  { sector: "Creative & Design", name: "Video Editing" },

  // Agriculture
  { sector: "Agriculture", name: "AgriTech" },
  { sector: "Agriculture", name: "Animal Farming" },
  { sector: "Agriculture", name: "Aquaculture" },
  { sector: "Agriculture", name: "Crop Farming" },
  { sector: "Agriculture", name: "Dairy Farming" },
  { sector: "Agriculture", name: "Fertilizers & Pesticides" },
  { sector: "Agriculture", name: "Food Processing" },
  { sector: "Agriculture", name: "Forestry" },
  { sector: "Agriculture", name: "Horticulture" },
  { sector: "Agriculture", name: "Organic Farming" },
  { sector: "Agriculture", name: "Poultry" },

  // Travel & Hospitality
  { sector: "Travel & Hospitality", name: "Airlines" },
  { sector: "Travel & Hospitality", name: "Car Rentals" },
  { sector: "Travel & Hospitality", name: "Cruise Lines" },
  { sector: "Travel & Hospitality", name: "Event Management" },
  { sector: "Travel & Hospitality", name: "Hotels & Resorts" },
  { sector: "Travel & Hospitality", name: "Online Travel Agencies" },
  { sector: "Travel & Hospitality", name: "Theme Parks" },
  { sector: "Travel & Hospitality", name: "Tourism" },
  { sector: "Travel & Hospitality", name: "Travel Technology" },
  { sector: "Travel & Hospitality", name: "Vacation Rentals" },

  // Government & Public Sector
  { sector: "Government & Public Sector", name: "Defense" },
  { sector: "Government & Public Sector", name: "Emergency Services" },
  { sector: "Government & Public Sector", name: "Government Administration" },
  { sector: "Government & Public Sector", name: "International Development" },
  { sector: "Government & Public Sector", name: "Law Enforcement" },
  { sector: "Government & Public Sector", name: "Military" },
  { sector: "Government & Public Sector", name: "NGO & Nonprofits" },
  { sector: "Government & Public Sector", name: "Public Health" },
  { sector: "Government & Public Sector", name: "Public Policy" },
  { sector: "Government & Public Sector", name: "Social Services" },

  // Beauty & Wellness
  { sector: "Beauty & Wellness", name: "Cosmetics" },
  { sector: "Beauty & Wellness", name: "Fitness & Gym" },
  { sector: "Beauty & Wellness", name: "Hair Care" },
  { sector: "Beauty & Wellness", name: "Health & Wellness" },
  { sector: "Beauty & Wellness", name: "Meditation & Mindfulness" },
  { sector: "Beauty & Wellness", name: "Nail Care" },
  { sector: "Beauty & Wellness", name: "Personal Care Products" },
  { sector: "Beauty & Wellness", name: "Salon & Spa" },
  { sector: "Beauty & Wellness", name: "Skin Care" },
  { sector: "Beauty & Wellness", name: "Yoga" },

  // Legal
  { sector: "Legal", name: "Corporate Law" },
  { sector: "Legal", name: "Criminal Law" },
  { sector: "Legal", name: "Family Law" },
  { sector: "Legal", name: "Immigration Law" },
  { sector: "Legal", name: "Intellectual Property" },
  { sector: "Legal", name: "Labor & Employment Law" },
  { sector: "Legal", name: "Legal Tech" },
  { sector: "Legal", name: "Litigation" },
  { sector: "Legal", name: "Paralegal Services" },
  { sector: "Legal", name: "Real Estate Law" },
  { sector: "Legal", name: "Tax Law" },

  // Sports & Recreation
  { sector: "Sports & Recreation", name: "eSports" },
  { sector: "Sports & Recreation", name: "Fitness Equipment" },
  { sector: "Sports & Recreation", name: "Outdoor Recreation" },
  { sector: "Sports & Recreation", name: "Professional Sports" },
  { sector: "Sports & Recreation", name: "Sports Analytics" },
  { sector: "Sports & Recreation", name: "Sports Broadcasting" },
  { sector: "Sports & Recreation", name: "Sports Management" },
  { sector: "Sports & Recreation", name: "Sports Medicine" },
  { sector: "Sports & Recreation", name: "Sports Retail" },
  { sector: "Sports & Recreation", name: "Youth Sports" },

  // Environment & Sustainability
  { sector: "Environment & Sustainability", name: "Carbon Credits" },
  { sector: "Environment & Sustainability", name: "Clean Tech" },
  { sector: "Environment & Sustainability", name: "Environmental Consulting" },
  { sector: "Environment & Sustainability", name: "Recycling & Waste Management" },
  { sector: "Environment & Sustainability", name: "Renewable Energy" },
  { sector: "Environment & Sustainability", name: "Sustainable Agriculture" },
  { sector: "Environment & Sustainability", name: "Sustainable Fashion" },
  { sector: "Environment & Sustainability", name: "Water Management" },
];

async function main() {
  console.log(`Seeding ${industries.length} industries...`);
  
  let inserted = 0;
  for (const industry of industries) {
    await prisma.industry.upsert({
      where: { name: industry.name },
      update: { sector: industry.sector },
      create: { name: industry.name, sector: industry.sector },
    });
    inserted++;
  }
  
  console.log(`✅ Successfully seeded ${inserted} industries across sectors.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
